[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
coffee_stylus = "YourProgramIDWillBeHereAfterDeployment"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
